614 add soft delete for offerings
ministryofjustice/hmpps-accredited-programmes-api pull request #114
Opened 2023-09-18 09:23 UTC by bell-pa

## Context

Trello: [Update Courses, Prerequisites, Offerings instead of replacing](https://trello.com/c/sooyolH2/614-add-scripts-for-updating-course-offering-data-in-the-service)

## Changes in this PR

* Added a `withdrawn` property to `Offering`
* Exclude withdrawn `Offering`s from course offering resources

## Release checklist

### Post-merge

- [ ] [Manually approve](../doc/how-to/perform-a-release.md#releasing-to-the-preprod-environment) release to preprod
- [ ] [Manually approve](../doc/how-to/perform-a-release.md#releasing-to-the-production-environment) release to prod

2023-09-18 15:52 UTC, bell-pa commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/jparepo/OfferingRepositoryTest.kt
> +  fun `find withdrawn offering by id`() {
I'll make changes in a tidying PR. 
Updating commits this far down the list, and subject to 3 pending PRs is going to be a pain.

2023-09-18 16:02 UTC, nsmj63-dxw requested changes
Minor niggles, mainly relating to naming, which will help me out with my refactoring ticket. Otherwise LGTM.

2023-09-18 16:02 UTC, nsmj63-dxw commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/domain/CourseServiceTest.kt
> +    fun `Active Offering be returned from courseOffering`() {
`Searching for an active course offering should return the correct result`?

2023-09-18 16:04 UTC, nsmj63-dxw approved these changes
I'm happy to make these naming changes in my PR, if it's easier. Approved.

2023-09-19 08:10 UTC, bell-pa commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/course/jparepo/OfferingRepositoryTest.kt
> +    val offering = courseRepository.save(course1).offerings.first()
In this case using first() is simply a convenient way of retrieving a single offering. No order implied.
I suppose I could retrieve a random item from the list but that might be confusing.
The ids are allocated by Hibernate, so aren't available until the tree of objects has been persisted.

2023-09-19 08:10 UTC, merged