862 first step - manual rebase
ministryofjustice/hmpps-accredited-programmes-api pull request #129
Opened 2023-09-27 10:47 UTC by bell-pa

Created by applying the changed files from [862 add programme history fields - first step](https://github.com/ministryofjustice/hmpps-accredited-programmes-api/pull/124) to the head of main by hand. Please refer to the referenced PR for further explanation and individual commit comments.

I have picked up some test method name changes from main, but making use of the data factories created by Nick will have to wait until after the second batch of changes from [862 add programme history audit fields - second step](https://github.com/ministryofjustice/hmpps-accredited-programmes-api/pull/126) have been applied.

Also reworked (simplified?) `RandomDataGenerators` and added more unit tests to `RandomDataGeneratorsTest`

### Post-merge

- [ ] [Manually approve](../doc/how-to/perform-a-release.md#releasing-to-the-preprod-environment) release to preprod
- [ ] [Manually approve](../doc/how-to/perform-a-release.md#releasing-to-the-production-environment) release to prod

2023-09-27 11:18 UTC, Gweaton requested changes
Thanks for making these changes, sorry you've had to redo this after the big refactor.

I'd like you to split up this one single commit into a few smaller ones, as we usually do, for documenting the reasons behind the changes so they live alongside the code for future reasons. I've lost count of the number of times reading through well-written history has clarified something for me. I appreciate you've linked to the other PR but that adds another step for readers to look through. As mentioned previously, having this split up into smaller PRs would also make the job easier for reviewers to see why things have changed.

I'm happy to pair on re-committing this with you, but if you'd like to have a go yourself, here's how I'd split it (order may change):

```
Use allOf keyword to simplify OpenAPI schemas

OpenAPI specifications provide an allOf keyword which provides an inheritance mechanism for component schemas. allOf has been used to remove some of the redundancy in api.yml.

OpenApi Operation objects have an operationId field that name each operation. If an operationId on an operation then the kotlin-spring code generator uses the value of this field as the name of the generated method that handles this operation. operationIds have been added to all the course-participation related operations in api.yml. Hopefully this makes the generated method names more readable. It also means that those method names do not change when the operation paths are changed. A future refactoring could add operationIds to all operations in the api.yml specification.
```
```
Tweak CourseParticipation fields to match designs

Expanded the setting and outcome properties of CourseParticipationHistory
* yearStarted has been moved to outcome, see below
* setting now has var location: String? and var type: CourseSetting
* outcome now has additional properties var yearStarted: Year? and var yearCompleted: Year?`

outcome has an additional unused private field
@Formula("0")
val ignoreMe: Int = 0

If all properties of an @Embedded object are null Hibernate will not create the object. Instead the property (outcome) is set null - even if it is not a nullable type! The additional field ignoreMe, which not nullable forces Hibernate to always populate the outcome property with an instance of CourseOutcome

The course_participation_history table has been renamed to course_participation
```
```
Simplify RandomDataGenerators and add unit tests

[Explanation of how these are simplified for future readers and code reviewers]
```

2023-09-27 11:18 UTC, Gweaton commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/CourseParticipationControllerTest.kt
> +    fun `get participation history by id - not found`() {
Can we put this back to the more descriptive version please?

2023-09-27 11:18 UTC, Gweaton commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/CourseParticipationControllerTest.kt
> +    fun `get participation history by id - bad uuid`() {
and the same here.

2023-09-27 11:18 UTC, Gweaton commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/CourseParticipationIntegrationTest.kt
> +  fun `find course participation  by prison number returns no matches`() {
Let's put this one back to the more verbose version please.

2023-09-28 14:47 UTC, Gweaton reviewed
Thanks a lot for redoing those commits, I know it must have taken a while, but it's a lot easier to review like this.

Have just left a couple of small comments, which you should be able to squash in with `git commit --amend --no-edit` (as they're on the final commit) and a force push.

2023-09-28 15:38 UTC, bell-pa commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/PeopleControllerTest.kt
> +    "uk.gov.justice.digital.hmpps.hmppsaccreditedprogrammesapi.common.restpapi",
Yes.  Didn't pick this up because it isn't needed. Fixed.

2023-09-28 15:39 UTC, bell-pa commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsaccreditedprogrammesapi/participationhistory/restapi/PeopleControllerTest.kt
> +    fun `it returns an array of results when course participations are found`() {
Oops. Fixed.

2023-09-28 15:56 UTC, Gweaton approved these changes
Thank you!

2023-09-28 15:59 UTC, merged